### ISSUE TITLE
Date duplication when pressing the browsers back button

### ISSUE THREAD

**Issue by duianto** [lvarayut/github-date-of-creation#2]
The creation date gets duplicated, every time one returns to a github repositories main page, using the browsers back button.

#### Steps to reproduce
1. Open the page: https://github.com/lvarayut/github-date-of-creation
2. Click on a directory or file, for example the directory `icons`
3. Navigate back to the previous page, using the browsers back button

#### Observed behaviour
A second entry of the creation date has been added, pushing the rest of the entries (commits, branch, releases, etc.) to the left, so that they are evenly spaced.

Every time another directory or file is opened and one navigates back to the repositories main page (with the browsers back button), results in an additional creation date entry.

They start overlapping after 8 duplicates.
![chrome_2017-10-27_09-11-25](https://user-images.githubusercontent.com/13420573/32092999-ff6df17a-bafa-11e7-8ac9-0da550c65e32.png)

#### Expected behaviour
The creation date should not be duplicated.

#### Possible solution
Maybe the script could check if there already is a creation date on the page, before it's added.

#### System info
Windows 10 Version 1607 (OS Build 14393.1770)
Google Chrome Version 62.0.3202.75 (Official Build) (64-bit)
Google Chrome Extension: Github - Date of creation 1.0.0
(I have other extensions installed, If the steps above aren't reproducible, then I can try it with the other extensions disabled.)

**Comment by lvarayut** [comment]
Thanks @duianto for reporting, I'll check it soon or any PR would be really welcome

**Comment by lvarayut** [comment]
The issue has been fixed in 83449ee
