### ISSUE TITLE
private repository dates not supported

### ISSUE THREAD

**Issue by lastlink** [lvarayut/github-date-of-creation#3]
It only shows the current month and year. Maybe this was planned, perhaps if you could do an optional sign in for users so they can see dates for projects they have access to. Or maybe there is another reason behind this bug.

**Comment by lvarayut** [comment]
Thanks @lastlink for reporting. It seems to be duplicated with https://github.com/lvarayut/github-date-of-creation/issues/1. I'm going to close this issue for now, please feel free to continue the discussion there.
