### ISSUE TITLE
shows current date for all private repos I open

### ISSUE THREAD

**Issue by johnschn05** [lvarayut/github-date-of-creation#5]
If I am mistaken then I apologize, but I thought this would display the date a repo was created, not the current date.  Every private repo I look at, it shows todays date.  Does this work with private repos?  Seems to work with public ones ok.

**Comment by lvarayut** [comment]
Thanks @johnschn05 for reporting. It seems to be duplicated with #1. I'm going to close this issue, for now, please feel free to continue the discussion there.
