### ISSUE TITLE
Firefox addon

### ISSUE THREAD

**Issue by EvPix** [lvarayut/github-date-of-creation#7]
This addon would be useful in Firefox. And sometimes me(or anyone) need to find out the date of creation of the repository quickly.

**Comment by lvarayut** [comment]
Thanks for your request, I completely agreed with you. If you could send a pull request for adding the Firefox addon, I'll be very happy merge it

**Comment by EvolutionPixG** [comment]
I myself do not use Firefox(I use a browser based on Chromium). But for those who use Firefox, this addon would be useful.
